######################################################################################
######################################################################################
# DATABASE AND ANALYTICS PROGRAMMING: LAB-4

## Submission by: __AMANDEEP SINGH__ (x19194137)
######################################################################################
######################################################################################

---

# Q1-EXCEPTION HANDLING:

---

## Q1 (a)

Create a text file and manually add some data to the file

## Q1 (b)

Write Python code to
- open the file for write only access
- attempt to read the contents of the file

## Q1 (c)

Note the type of Error that has been raised.

## Q1 (d)

Modify your code to
- use a try / except / finally construct that will catch the exception, print a user-friendly error message, and clean up the file resource

## Q1 (e)

Investigate how you would create your own Exception class. Then create your own Exception class and use it in your code from the previous exercise.

---

# Q2-NUMPY EXERCISE A:

---

## Q2 (a)

Create an array with the arange function and reshape the array as follows:

    b = arange(24).reshape(2,3,4)
    
This gives us a 3-dimensional data structure – you can think of it as being like 2
spreadsheet sheets where each sheet contains 3 rows of data and each row
contains 4 columns.
Using indexing and slicing perform the following tasks:

1) Choose the first set of 3 rows and 4 columns of data

2) Choose the second row of data from the second set of 3 rows of data

3) Choose all the data from the second column for both the first and second
sets of rows and columns of data 

In [17]:
import numpy as np

b = np.array(np.arange(24)).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
c = b[0, :, :]
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
d = b[1, :, :]
d

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
e = b[:, :, 1]
e

array([[ 1,  5,  9],
       [13, 17, 21]])

## Q2 (b)

Use the ravel function to flatten the data. What’s the difference between ravel
and flatten?

In [31]:
flat_b_ravel = np.ravel(b, 'C')
flat_b_ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
flat_b_flatten = b.flatten('C')
flat_b_flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [41]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Q2 (c)

Reshape the data so that there are 6 rows of 4 columns per row.

In [36]:
reshaped_b = np.array(np.arange(24)).reshape(1, 6, 4)
reshaped_b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
b.reshape(1, 6, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Q2 (d)

Get the transpose of the new data structure.

In [40]:
transpose_b = np.transpose(b)
transpose_b

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

## Q2 (e)

Restack the rows of the transposed data structure in reverse order 
>(hint: look at
the row_stack function).

## Q2 (f)

Split the resulting data structure horizontally 
>(hint: look at the hsplit function).

---

# Q3-NUMPY EXERCISE B:

---

> NOTE:

> The AAPL.csv contains some stock price data for Apple.

> The MSFT.csv contains some stock price data for Microsoft.

## Q3 (a)

Use the ___loadtxt___ command to load data from __AAPL.csv__ from columns 5 and 7 (i.e.,
the close price and the volume).

In [98]:
dtype_a = np.dtype([('Close', 'f8'), ('Volume', 'f8')])
col5, col7 = np.loadtxt('AAPL.csv', delimiter=",", dtype=dtype_a, skiprows=1, usecols=(4, 6), unpack=True)

In [99]:
np.shape(col5)

(252,)

In [100]:
np.shape(col7)

(252,)

## Q3 (b)

Based on the data provided, calculate the volume weighted average price for the
stock (i.e., calculate the average price using the volume as weight values). 

In [101]:
dtype_b = np.dtype([('High', 'f8'), ('Low', 'f8'), ('Close', 'f8'), ('Volume', 'f8')])
high, low, close, volume = np.loadtxt('AAPL.csv', delimiter=",", dtype=dtype_b, skiprows=1, usecols=(2, 3, 4, 6), unpack=True)

In [103]:
vwap = np.sum(((high+low+close)/3)*volume)/np.sum(volume) #volume weighted average price
vwap

190.08407597762957

## Q3 (c)

Calculate the median value of the closing prices 
>(hint: use the median function).

In [79]:
np.median(close)

197.0

## Q3 (d)

Calculate the variance value of the closing prices.

In [83]:
np.var(close, ddof=0)

432.8804568188714

In [84]:
np.var(close, ddof=1)

434.6050801528111

In [113]:
# Confirm which ddof to use in the variance function, there is a statistical difference between the two. 

## Q3 (e)

Again, use the __loadtxt__ command to load data from columns 3 and 4 (i.e., the high
prices and the low prices).

In [104]:
dtype_e = np.dtype([('High', 'f8'), ('Low', 'f8')])
col3, col4 = np.loadtxt('AAPL.csv', delimiter=",", dtype=dtype_e, skiprows=1, usecols=(2, 3), unpack=True)

In [105]:
np.shape(col3)

(252,)

In [106]:
np.shape(col4)

(252,)

## Q3 (f)

Use the __max__ and __min__ functions to get the highest high and the lowest low value.

In [88]:
max(high)

229.929993

In [89]:
min(low)

142.0

In [90]:
np.max(high)

229.929993

In [91]:
np.min(low)

142.0

## Q3 (g)

Load data from column 5 of __AAPL.csv__. Also, load data from column 5 of __MSFT.csv__.

In [134]:
col5_AAPL = np.loadtxt('AAPL.csv', delimiter=",", dtype='float', skiprows=1, usecols=4)
col5_MSFT = np.loadtxt('MSFT.csv', delimiter=",", dtype='float', skiprows=1, usecols=4)

In [135]:
np.shape(col5_AAPL)

(252,)

In [136]:
np.shape(col5_MSFT)

(252,)

## Q3 (h)

Calculate the covariance matrix of the closing prices of AAPL and MSFT 
>(hint: use
the cov function).

In [140]:
cov_matrix = np.cov(col5_AAPL, col5_MSFT)
cov_matrix

array([[434.60508015, 186.97834783],
       [186.97834783, 184.73421932]])

## Q3 (i)

View the values on the diagonal 
> (hint: diagonal).

In [141]:
np.diagonal(cov_matrix)

array([434.60508015, 184.73421932])

## Q3 (j)

Calculate the correlation coefficient of the closing prices of AAPL and MSFT 
>(hint:
corrcoef).

In [144]:
R_matrix = np.corrcoef(cov_matrix)
R_matrix

array([[1., 1.],
       [1., 1.]])

---

# Q4-REGULAR EXPRESSIONS:

Write a Python program that will identify URLs using regular expressions.

---

In [148]:
import re

full_text = "Kabhi kabhi apun ko lagta hai ki https://stackoverflow.com/ hi bhagwaan hai"

urls_in_full_text = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', full_text)

print("Original string: ", full_text)
print("Urls: ", urls_in_full_text)

Original string:  Kabhi kabhi apun ko lagta hai ki https://stackoverflow.com/ hi bhagwaan hai
Urls:  ['https://stackoverflow.com/']


---

# Q5-TEXT ANALYTICS:

Complete the tutorial at https://data-flair.training/blogs/nltk-python-tutorial/

---